'use client'

import { createContext, useContext, useState, ReactNode, useEffect } from 'react'

export type Language = 'ru' | 'uz' | 'en'

export const translations = {
  ru: {
    // Navigation
    dashboard: 'Панель управления',
    drugs: 'Препараты',
    inventory: 'Склад',
    pharmacies: 'Аптеки',
    suppliers: 'Поставщики',
    sales: 'Продажи',
    analytics: 'Аналитика',
    settings: 'Настройки',
    menu: 'Меню',

    // Dashboard
    welcomeMessage: 'Добро пожаловать в PharmaCentral',
    totalDrugs: 'Всего препаратов',
    totalInventory: 'Стоимость склада',
    todaySales: 'Продажи сегодня',
    lowStock: 'Мало на складе',
    recentTransactions: 'Последние операции',
    topSellingDrugs: 'Топ продаж',
    inventoryByPharmacy: 'Склад по аптекам',
    expiringItems: 'Истекает срок',
    salesThisWeek: 'Продажи за неделю',
    inventoryDistribution: 'Распределение склада',
    lowStockAlert: 'Низкий запас',
    expiryAlert: 'Истекает срок годности',
    perWeek: 'за неделю',
    perMonth: 'за месяц',
    vsYesterday: 'vs вчера',
    needsAttention: 'Требует внимания',
    allOperations: 'Все операции',
    today: 'Сегодня',
    share: 'Доля',
    overview: 'Обзор системы',
    viewAll: 'Показать все',

    // Common
    add: 'Добавить',
    edit: 'Редактировать',
    delete: 'Удалить',
    save: 'Сохранить',
    cancel: 'Отмена',
    search: 'Поиск',
    noData: 'Нет данных',
    filter: 'Фильтр',
    filters: 'Фильтры',
    export: 'Экспорт',
    import: 'Импорт',
    actions: 'Действия',
    status: 'Статус',
    active: 'Активный',
    inactive: 'Неактивный',
    all: 'Все',
    name: 'Название',
    quantity: 'Количество',
    price: 'Цена',
    date: 'Дата',
    region: 'Регион',
    close: 'Закрыть',
    details: 'Подробнее',
    more: 'Ещё',
    loading: 'Загрузка...',
    pcs: 'шт',
    days: 'дн',
    found: 'Найдено',
    showing: 'Показано',
    of: 'из',
    positions: 'позиций',

    // Drugs
    drugName: 'Наименование препарата',
    drug: 'Препарат',
    drugCatalog: 'Каталог лекарственных препаратов с классификацией АТХ',
    inn: 'МНН',
    atxCode: 'Код АТХ',
    atxClassification: 'Классификация АТХ',
    therapeuticGroup: 'Терапевтическая группа',
    allGroups: 'Все группы',
    form: 'Форма выпуска',
    dosage: 'Дозировка',
    manufacturer: 'Производитель',
    prescription: 'Рецептурный',
    barcode: 'Штрих-код',
    tradeName: 'Торговое название',
    englishName: 'Английское название',
    addDrug: 'Добавить препарат',
    searchDrugs: 'Поиск по названию, МНН, АТХ...',
    selectGroup: 'Выберите группу',
    selectForm: 'Выберите форму',
    prescriptionDrug: 'Рецептурный препарат (Rx)',
    country: 'Страна',
    countryOfOrigin: 'Страна производства',

    // Inventory
    inventoryManagement: 'Управление запасами и остатками по аптекам',
    purchasePrice: 'Цена закупки',
    salePrice: 'Цена продажи',
    batchNumber: 'Номер партии',
    batch: 'Партия',
    expiryDate: 'Срок годности',
    expiryTo: 'Срок до',
    minStock: 'Мин. запас',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    stockStatus: 'Статус запаса',
    normal: 'В норме',
    low: 'Низкий',
    critical: 'Критический',
    stockReceiving: 'Приход товара',
    transfer: 'Перемещение',
    positionsOnStock: 'Позиций на складе',
    totalCost: 'Общая стоимость',
    expiringLess90: 'Истекает срок (<90 дн)',
    searchInventory: 'Поиск по названию, партии...',
    allPharmacies: 'Все аптеки',
    supplier: 'Поставщик',
    current: 'Текущий',
    min: 'Мин.',

    // Transactions
    sale: 'Продажа',
    purchase: 'Закупка',
    return: 'Возврат',
    totalAmount: 'Сумма',
    unitPrice: 'Цена за ед.',
    transactionHistory: 'История транзакций и управление продажами',
    salesAndOperations: 'Продажи и операции',
    allOperationsType: 'Все операции',
    purchases: 'Закупки',
    returns: 'Возвраты',
    transfers: 'Перемещения',
    newSale: 'Новая продажа',
    document: 'Документ',
    dateTime: 'Дата/Время',
    salesToday: 'Продажи сегодня',
    purchasesToday: 'Закупки сегодня',
    totalOperations: 'Всего операций',
    pointOfSale: 'Точка продаж',
    currentOrder: 'Текущий заказ',
    completeSale: 'Завершить продажу',
    subtotal: 'Итого',
    cartEmpty: 'Корзина пуста',
    selectProducts: 'Выберите товары',
    items: 'товаров',
    startNewSale: 'Новая продажа',
    viewSalesHistory: 'История продаж',
    loadingProducts: 'Загрузка товаров...',
    noProductsFound: 'Товары не найдены',
    transactionCompleted: 'Транзакция успешно завершена',
    checkoutFailed: 'Ошибка оплаты. Попробуйте снова.',

    // Pharmacies
    pharmacyNetwork: 'Управление аптечной сетью',
    pharmacy: 'Аптека',
    addPharmacy: 'Добавить аптеку',
    pharmacyName: 'Название аптеки',
    district: 'Район',
    address: 'Адрес',
    fullAddress: 'Полный адрес',
    phone: 'Телефон',
    email: 'Email',
    manager: 'Заведующий',
    managerName: 'ФИО заведующего',
    activePharmacies: 'Активных аптек',
    totalStock: 'Общий склад',
    regionsCount: 'Регионов охвата',
    allRegions: 'Все регионы',
    drugsCount: 'Препаратов',
    stock: 'Склад',

    // Suppliers
    suppliersTitle: 'Производители, дистрибьюторы и импортеры',
    supplierName: 'Наименование поставщика',
    supplierType: 'Тип',
    distributorType: 'Дистрибьютор',
    manufacturerType: 'Производитель',
    importerType: 'Импортер',
    contact: 'Контакт',
    contactPerson: 'Контактное лицо',
    addSupplier: 'Добавить поставщика',
    companyName: 'Название компании',
    taxId: 'ИНН',
    taxNumber: 'Налоговый номер',
    activeSuppliers: 'Активных поставщиков',
    totalOrders: 'Заказов всего',
    totalTurnover: 'Общий оборот',
    countries: 'Стран',
    allTypes: 'Все типы',
    orders: 'Заказов',
    turnover: 'Оборот',
    searchSuppliers: 'Поиск по названию, стране...',

    // Analytics
    analyticsTitle: 'Статистика продаж, закупок и прибыли',
    salesAnalytics: 'Аналитика продаж',
    inventoryTurnover: 'Оборачиваемость',
    revenueByPeriod: 'Выручка по периодам',
    profitMargin: 'Маржинальность',
    week: 'Неделя',
    month: 'Месяц',
    quarter: 'Квартал',
    year: 'Год',
    exportReport: 'Экспорт отчёта',
    totalRevenue: 'Общая выручка',
    purchasesTotal: 'Закупки',
    profit: 'Прибыль',
    margin: 'Маржа',
    vsLastYear: 'vs прошлый год',
    salesAndPurchasesTrend: 'Динамика продаж и закупок',
    topDrugsByRevenue: 'Топ препаратов по выручке',
    salesByPharmacy: 'Продажи по аптекам',
    salesByCategory: 'Продажи по категориям',
    revenue: 'Выручка',

    // Settings
    settingsTitle: 'Конфигурация системы',
    general: 'Общие',
    currency: 'Валюта',
    notifications: 'Уведомления',
    users: 'Пользователи',
    database: 'База данных',
    security: 'Безопасность',
    generalSettings: 'Общие настройки',
    organizationName: 'Название организации',
    interfaceLanguage: 'Язык интерфейса',
    timezone: 'Часовой пояс',
    dateFormat: 'Формат даты',
    saveChanges: 'Сохранить изменения',
    currencySettings: 'Настройки валюты',
    mainCurrency: 'Основная валюта',
    exchangeRate: 'Курс USD к UZS',
    updateRate: 'Обновить курс',
    currencyHint: 'Курс валют используется для конвертации цен закупки и продажи. Рекомендуется обновлять курс ежедневно.',
    notificationSettings: 'Настройки уведомлений',
    lowStockNotification: 'Низкий запас товара',
    lowStockNotificationDesc: 'Уведомлять когда товар достигает минимального уровня',
    expiryNotification: 'Истекающий срок годности',
    expiryNotificationDesc: 'Уведомлять за 90 дней до истечения срока годности',
    largeSalesNotification: 'Крупные продажи',
    largeSalesNotificationDesc: 'Уведомлять о продажах свыше 1 000 000 сум',
    emailNotifications: 'Email уведомления',
    emailNotificationsDesc: 'Дублировать важные уведомления на email',
    userManagement: 'Управление пользователями',
    addUser: 'Добавить пользователя',
    user: 'Пользователь',
    role: 'Роль',
    admin: 'Администратор',
    managerRole: 'Менеджер',
    cashier: 'Кассир',
    backupDatabase: 'Создать резервную копию',
    restoreDatabase: 'Восстановить из копии',
    drugsCount2: 'Препаратов',
    inventoryRecords: 'Записей инвентаря',
    transactionsCount: 'Транзакций',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
    minChars: 'Минимум 8 символов',
    repeatPassword: 'Повторите новый пароль',
    updatePassword: 'Обновить пароль',

    // Drug forms
    tablets: 'Таблетки',
    capsules: 'Капсулы',
    solution: 'Раствор',
    powder: 'Порошок',
    gel: 'Гель',
    cream: 'Крем',
    syrup: 'Сироп',
    ointment: 'Мазь',
    drops: 'Капли',

    // CRUD operations
    deleteDrug: 'Удалить препарат',
    confirmDelete: 'Вы уверены, что хотите удалить',
    noDrugsFound: 'Препараты не найдены',
    addFirstDrug: 'Добавьте первый препарат в каталог',
    noInventoryFound: 'Склад пуст',
    deleteInventory: 'Удалить позицию',
    selectDrug: 'Выберите препарат',
    selectPharmacy: 'Выберите аптеку',
    selectSupplier: 'Выберите поставщика',
    invoiceNumber: 'Номер накладной',

    // Time
    minAgo: 'мин назад',
    hoursAgo: 'ч назад',
    daysAgo: 'дн назад',
  },

  uz: {
    // Navigation
    dashboard: 'Boshqaruv paneli',
    drugs: 'Dorilar',
    inventory: 'Ombor',
    pharmacies: 'Dorixonalar',
    suppliers: 'Yetkazib beruvchilar',
    sales: 'Sotuvlar',
    analytics: 'Tahlil',
    settings: 'Sozlamalar',
    menu: 'Menyu',

    // Dashboard
    welcomeMessage: 'PharmaCentral-ga xush kelibsiz',
    totalDrugs: 'Jami dorilar',
    totalInventory: 'Ombor qiymati',
    todaySales: 'Bugungi sotuvlar',
    lowStock: 'Kam qolgan',
    recentTransactions: 'Oxirgi operatsiyalar',
    topSellingDrugs: "Eng ko'p sotilgan",
    inventoryByPharmacy: "Dorixona bo'yicha ombor",
    expiringItems: 'Muddati tugayotgan',
    salesThisWeek: 'Haftalik sotuvlar',
    inventoryDistribution: 'Ombor taqsimoti',
    lowStockAlert: 'Kam zaxira',
    expiryAlert: 'Yaroqlilik muddati tugamoqda',
    perWeek: 'hafta uchun',
    perMonth: 'oy uchun',
    vsYesterday: 'kechaga nisbatan',
    needsAttention: "E'tibor kerak",
    allOperations: 'Barcha operatsiyalar',
    today: 'Bugun',
    share: 'Ulushi',
    overview: 'Tizim ko\'rinishi',
    viewAll: 'Hammasini ko\'rish',

    // Common
    add: "Qo'shish",
    edit: 'Tahrirlash',
    delete: "O'chirish",
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    search: 'Qidirish',
    noData: "Ma'lumotlar yo'q",
    filter: 'Filtr',
    filters: 'Filtrlar',
    export: 'Eksport',
    import: 'Import',
    actions: 'Amallar',
    status: 'Holat',
    active: 'Faol',
    inactive: 'Nofaol',
    all: 'Barchasi',
    name: 'Nomi',
    quantity: 'Miqdor',
    price: 'Narx',
    date: 'Sana',
    region: 'Viloyat',
    close: 'Yopish',
    details: 'Batafsil',
    more: 'Yana',
    loading: 'Yuklanmoqda...',
    pcs: 'dona',
    days: 'kun',
    found: 'Topildi',
    showing: "Ko'rsatilmoqda",
    of: 'dan',
    positions: 'pozitsiya',

    // Drugs
    drugName: 'Dori nomi',
    drug: 'Dori',
    drugCatalog: 'ATX klassifikatsiyali dorilar katalogi',
    inn: 'XNN',
    atxCode: 'ATX kodi',
    atxClassification: 'ATX klassifikatsiyasi',
    therapeuticGroup: 'Terapevtik guruh',
    allGroups: 'Barcha guruhlar',
    form: 'Shakli',
    dosage: 'Dozasi',
    manufacturer: 'Ishlab chiqaruvchi',
    prescription: 'Retseptli',
    barcode: 'Shtrix-kod',
    tradeName: 'Savdo nomi',
    englishName: 'Inglizcha nomi',
    addDrug: "Dori qo'shish",
    searchDrugs: 'Nom, XNN, ATX boyicha qidirish...',
    selectGroup: 'Guruhni tanlang',
    selectForm: 'Shaklni tanlang',
    prescriptionDrug: 'Retseptli dori (Rx)',
    country: 'Davlat',
    countryOfOrigin: 'Ishlab chiqarish davlati',

    // Inventory
    inventoryManagement: "Dorixonalar bo'yicha zaxira va qoldiqlarni boshqarish",
    purchasePrice: 'Sotib olish narxi',
    salePrice: 'Sotish narxi',
    batchNumber: 'Partiya raqami',
    batch: 'Partiya',
    expiryDate: 'Yaroqlilik muddati',
    expiryTo: 'Muddat',
    minStock: 'Min. zaxira',
    inStock: 'Mavjud',
    outOfStock: 'Mavjud emas',
    stockStatus: 'Zaxira holati',
    normal: 'Normal',
    low: 'Kam',
    critical: 'Kritik',
    stockReceiving: 'Tovar qabul qilish',
    transfer: "Ko'chirish",
    positionsOnStock: 'Ombordagi pozitsiyalar',
    totalCost: 'Jami qiymat',
    expiringLess90: 'Muddati tugayotgan (<90 kun)',
    searchInventory: 'Nom, partiya boyicha qidirish...',
    allPharmacies: 'Barcha dorixonalar',
    supplier: 'Yetkazib beruvchi',
    current: 'Joriy',
    min: 'Min.',

    // Transactions
    sale: 'Sotish',
    purchase: 'Sotib olish',
    return: 'Qaytarish',
    totalAmount: 'Jami summa',
    unitPrice: 'Birlik narxi',
    transactionHistory: "Tranzaksiyalar tarixi va sotuvlarni boshqarish",
    salesAndOperations: 'Sotuvlar va operatsiyalar',
    allOperationsType: 'Barcha operatsiyalar',
    purchases: 'Xaridlar',
    returns: 'Qaytarishlar',
    transfers: "Ko'chirishlar",
    newSale: 'Yangi sotuv',
    document: 'Hujjat',
    dateTime: 'Sana/Vaqt',
    salesToday: 'Bugungi sotuvlar',
    purchasesToday: 'Bugungi xaridlar',
    totalOperations: 'Jami operatsiyalar',
    pointOfSale: 'Sotuv nuqtasi',
    currentOrder: 'Joriy buyurtma',
    completeSale: 'Sotuvni yakunlash',
    subtotal: 'Jami',
    cartEmpty: "Savat bo'sh",
    selectProducts: 'Mahsulotlarni tanlang',
    items: 'dona',
    startNewSale: 'Yangi sotuv',
    viewSalesHistory: 'Sotuvlar tarixi',
    loadingProducts: 'Mahsulotlar yuklanmoqda...',
    noProductsFound: 'Mahsulotlar topilmadi',
    transactionCompleted: 'Tranzaksiya muvaffaqiyatli yakunlandi',
    checkoutFailed: "Xatolik. Qayta urinib ko'ring.",

    // Pharmacies
    pharmacyNetwork: "Dorixona tarmog'ini boshqarish",
    pharmacy: 'Dorixona',
    addPharmacy: "Dorixona qo'shish",
    pharmacyName: 'Dorixona nomi',
    district: 'Tuman',
    address: 'Manzil',
    fullAddress: "To'liq manzil",
    phone: 'Telefon',
    email: 'Email',
    manager: 'Mudira',
    managerName: 'Mudira FIO',
    activePharmacies: 'Faol dorixonalar',
    totalStock: 'Jami ombor',
    regionsCount: 'Viloyatlar soni',
    allRegions: 'Barcha viloyatlar',
    drugsCount: 'Dorilar',
    stock: 'Ombor',

    // Suppliers
    suppliersTitle: "Ishlab chiqaruvchilar, distribyutorlar va importchilar",
    supplierName: 'Yetkazib beruvchi nomi',
    supplierType: 'Turi',
    distributorType: 'Distribyutor',
    manufacturerType: 'Ishlab chiqaruvchi',
    importerType: 'Importchi',
    contact: 'Aloqa',
    contactPerson: "Bog'lanish uchun shaxs",
    addSupplier: "Yetkazib beruvchi qo'shish",
    companyName: 'Kompaniya nomi',
    taxId: 'INN',
    taxNumber: 'Soliq raqami',
    activeSuppliers: 'Faol yetkazib beruvchilar',
    totalOrders: 'Jami buyurtmalar',
    totalTurnover: 'Jami aylanma',
    countries: 'Davlatlar',
    allTypes: 'Barcha turlar',
    orders: 'Buyurtmalar',
    turnover: 'Aylanma',
    searchSuppliers: 'Nom, davlat boyicha qidirish...',

    // Analytics
    analyticsTitle: 'Sotuvlar, xaridlar va foyda statistikasi',
    salesAnalytics: 'Sotuvlar tahlili',
    inventoryTurnover: 'Aylanish',
    revenueByPeriod: "Davrlar bo'yicha daromad",
    profitMargin: 'Daromadlilik',
    week: 'Hafta',
    month: 'Oy',
    quarter: 'Chorak',
    year: 'Yil',
    exportReport: 'Hisobotni eksport qilish',
    totalRevenue: 'Jami daromad',
    purchasesTotal: 'Xaridlar',
    profit: 'Foyda',
    margin: 'Marja',
    vsLastYear: "o'tgan yilga nisbatan",
    salesAndPurchasesTrend: 'Sotuvlar va xaridlar dinamikasi',
    topDrugsByRevenue: "Daromad bo'yicha top dorilar",
    salesByPharmacy: "Dorixonalar bo'yicha sotuvlar",
    salesByCategory: "Kategoriyalar bo'yicha sotuvlar",
    revenue: 'Daromad',

    // Settings
    settingsTitle: 'Tizim konfiguratsiyasi',
    general: 'Umumiy',
    currency: 'Valyuta',
    notifications: 'Bildirishnomalar',
    users: 'Foydalanuvchilar',
    database: "Ma'lumotlar bazasi",
    security: 'Xavfsizlik',
    generalSettings: 'Umumiy sozlamalar',
    organizationName: 'Tashkilot nomi',
    interfaceLanguage: 'Interfeys tili',
    timezone: 'Vaqt zonasi',
    dateFormat: 'Sana formati',
    saveChanges: "O'zgarishlarni saqlash",
    currencySettings: 'Valyuta sozlamalari',
    mainCurrency: 'Asosiy valyuta',
    exchangeRate: 'USD/UZS kursi',
    updateRate: 'Kursni yangilash',
    currencyHint: "Valyuta kursi sotib olish va sotish narxlarini konvertatsiya qilish uchun ishlatiladi. Kursni har kuni yangilash tavsiya etiladi.",
    notificationSettings: 'Bildirishnoma sozlamalari',
    lowStockNotification: 'Kam zaxira',
    lowStockNotificationDesc: "Tovar minimal darajaga yetganda xabar berish",
    expiryNotification: 'Yaroqlilik muddati',
    expiryNotificationDesc: "Yaroqlilik muddati tugashidan 90 kun oldin xabar berish",
    largeSalesNotification: 'Katta sotuvlar',
    largeSalesNotificationDesc: "1 000 000 so'mdan ortiq sotuvlar haqida xabar berish",
    emailNotifications: 'Email bildirishnomalar',
    emailNotificationsDesc: "Muhim bildirishnomalarni emailga yuborish",
    userManagement: 'Foydalanuvchilarni boshqarish',
    addUser: "Foydalanuvchi qo'shish",
    user: 'Foydalanuvchi',
    role: 'Vazifa',
    admin: 'Administrator',
    managerRole: 'Menejer',
    cashier: 'Kassir',
    backupDatabase: 'Zaxira nusxa yaratish',
    restoreDatabase: 'Zaxiradan tiklash',
    drugsCount2: 'Dorilar',
    inventoryRecords: 'Ombor yozuvlari',
    transactionsCount: 'Tranzaksiyalar',
    currentPassword: 'Joriy parol',
    newPassword: 'Yangi parol',
    confirmPassword: 'Parolni tasdiqlang',
    minChars: 'Kamida 8 belgi',
    repeatPassword: 'Yangi parolni takrorlang',
    updatePassword: 'Parolni yangilash',

    // Drug forms
    tablets: 'Tabletkalar',
    capsules: 'Kapsulalar',
    solution: 'Eritma',
    powder: 'Kukun',
    gel: 'Gel',
    cream: 'Krem',
    syrup: 'Sirop',
    ointment: 'Malham',
    drops: 'Tomchilar',

    // CRUD operations
    deleteDrug: "Dorini o'chirish",
    confirmDelete: "O'chirishni tasdiqlaysizmi",
    noDrugsFound: 'Dorilar topilmadi',
    addFirstDrug: "Katalogga birinchi dorini qo'shing",
    noInventoryFound: 'Ombor bo\'sh',
    deleteInventory: "Pozitsiyani o'chirish",
    selectDrug: 'Dorini tanlang',
    selectPharmacy: 'Dorixonani tanlang',
    selectSupplier: 'Yetkazib beruvchini tanlang',
    invoiceNumber: 'Faktura raqami',

    // Time
    minAgo: 'daqiqa oldin',
    hoursAgo: 'soat oldin',
    daysAgo: 'kun oldin',
  },

  en: {
    // Navigation
    dashboard: 'Dashboard',
    drugs: 'Drugs',
    inventory: 'Inventory',
    pharmacies: 'Pharmacies',
    suppliers: 'Suppliers',
    sales: 'Sales',
    analytics: 'Analytics',
    settings: 'Settings',
    menu: 'Menu',

    // Dashboard
    welcomeMessage: 'Welcome to PharmaCentral',
    totalDrugs: 'Total Drugs',
    totalInventory: 'Inventory Value',
    todaySales: "Today's Sales",
    lowStock: 'Low Stock',
    recentTransactions: 'Recent Transactions',
    topSellingDrugs: 'Top Selling',
    inventoryByPharmacy: 'Inventory by Pharmacy',
    expiringItems: 'Expiring Soon',
    salesThisWeek: 'Sales This Week',
    inventoryDistribution: 'Inventory Distribution',
    lowStockAlert: 'Low Stock Alert',
    expiryAlert: 'Expiry Alert',
    perWeek: 'per week',
    perMonth: 'per month',
    vsYesterday: 'vs yesterday',
    needsAttention: 'Needs attention',
    allOperations: 'All Operations',
    today: 'Today',
    share: 'Share',
    overview: 'System Overview',
    viewAll: 'View All',

    // Common
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    noData: 'No data available',
    filter: 'Filter',
    filters: 'Filters',
    export: 'Export',
    import: 'Import',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    name: 'Name',
    quantity: 'Quantity',
    price: 'Price',
    date: 'Date',
    region: 'Region',
    close: 'Close',
    details: 'Details',
    more: 'More',
    loading: 'Loading...',
    pcs: 'pcs',
    days: 'd',
    found: 'Found',
    showing: 'Showing',
    of: 'of',
    positions: 'positions',

    // Drugs
    drugName: 'Drug Name',
    drug: 'Drug',
    drugCatalog: 'Drug catalog with ATX classification',
    inn: 'INN',
    atxCode: 'ATX Code',
    atxClassification: 'ATX Classification',
    therapeuticGroup: 'Therapeutic Group',
    allGroups: 'All Groups',
    form: 'Form',
    dosage: 'Dosage',
    manufacturer: 'Manufacturer',
    prescription: 'Prescription',
    barcode: 'Barcode',
    tradeName: 'Trade Name',
    englishName: 'English Name',
    addDrug: 'Add Drug',
    searchDrugs: 'Search by name, INN, ATX...',
    selectGroup: 'Select group',
    selectForm: 'Select form',
    prescriptionDrug: 'Prescription drug (Rx)',
    country: 'Country',
    countryOfOrigin: 'Country of origin',

    // Inventory
    inventoryManagement: 'Stock and inventory management by pharmacy',
    purchasePrice: 'Purchase Price',
    salePrice: 'Sale Price',
    batchNumber: 'Batch Number',
    batch: 'Batch',
    expiryDate: 'Expiry Date',
    expiryTo: 'Expires',
    minStock: 'Min. Stock',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    stockStatus: 'Stock Status',
    normal: 'Normal',
    low: 'Low',
    critical: 'Critical',
    stockReceiving: 'Receive Stock',
    transfer: 'Transfer',
    positionsOnStock: 'Positions in Stock',
    totalCost: 'Total Cost',
    expiringLess90: 'Expiring (<90 days)',
    searchInventory: 'Search by name, batch...',
    allPharmacies: 'All Pharmacies',
    supplier: 'Supplier',
    current: 'Current',
    min: 'Min.',

    // Transactions
    sale: 'Sale',
    purchase: 'Purchase',
    return: 'Return',
    totalAmount: 'Total Amount',
    unitPrice: 'Unit Price',
    transactionHistory: 'Transaction history and sales management',
    salesAndOperations: 'Sales & Operations',
    allOperationsType: 'All operations',
    purchases: 'Purchases',
    returns: 'Returns',
    transfers: 'Transfers',
    newSale: 'New Sale',
    document: 'Document',
    dateTime: 'Date/Time',
    salesToday: "Today's Sales",
    purchasesToday: "Today's Purchases",
    totalOperations: 'Total Operations',
    pointOfSale: 'Point of Sale',
    currentOrder: 'Current Order',
    completeSale: 'Complete Sale',
    subtotal: 'Subtotal',
    cartEmpty: 'Cart is empty',
    selectProducts: 'Select products to start',
    items: 'items',
    startNewSale: 'Start New Sale',
    viewSalesHistory: 'View Sales History',
    loadingProducts: 'Loading products...',
    noProductsFound: 'No products found',
    transactionCompleted: 'Transaction completed successfully',
    checkoutFailed: 'Checkout failed. Please try again.',

    // Pharmacies
    pharmacyNetwork: 'Pharmacy network management',
    pharmacy: 'Pharmacy',
    addPharmacy: 'Add Pharmacy',
    pharmacyName: 'Pharmacy Name',
    district: 'District',
    address: 'Address',
    fullAddress: 'Full Address',
    phone: 'Phone',
    email: 'Email',
    manager: 'Manager',
    managerName: 'Manager Name',
    activePharmacies: 'Active Pharmacies',
    totalStock: 'Total Stock',
    regionsCount: 'Regions',
    allRegions: 'All Regions',
    drugsCount: 'Drugs',
    stock: 'Stock',

    // Suppliers
    suppliersTitle: 'Manufacturers, distributors, and importers',
    supplierName: 'Supplier Name',
    supplierType: 'Type',
    distributorType: 'Distributor',
    manufacturerType: 'Manufacturer',
    importerType: 'Importer',
    contact: 'Contact',
    contactPerson: 'Contact Person',
    addSupplier: 'Add Supplier',
    companyName: 'Company Name',
    taxId: 'Tax ID',
    taxNumber: 'Tax Number',
    activeSuppliers: 'Active Suppliers',
    totalOrders: 'Total Orders',
    totalTurnover: 'Total Turnover',
    countries: 'Countries',
    allTypes: 'All Types',
    orders: 'Orders',
    turnover: 'Turnover',
    searchSuppliers: 'Search by name, country...',

    // Analytics
    analyticsTitle: 'Sales, purchases, and profit statistics',
    salesAnalytics: 'Sales Analytics',
    inventoryTurnover: 'Inventory Turnover',
    revenueByPeriod: 'Revenue by Period',
    profitMargin: 'Profit Margin',
    week: 'Week',
    month: 'Month',
    quarter: 'Quarter',
    year: 'Year',
    exportReport: 'Export Report',
    totalRevenue: 'Total Revenue',
    purchasesTotal: 'Purchases',
    profit: 'Profit',
    margin: 'Margin',
    vsLastYear: 'vs last year',
    salesAndPurchasesTrend: 'Sales & Purchases Trend',
    topDrugsByRevenue: 'Top Drugs by Revenue',
    salesByPharmacy: 'Sales by Pharmacy',
    salesByCategory: 'Sales by Category',
    revenue: 'Revenue',

    // Settings
    settingsTitle: 'System Configuration',
    general: 'General',
    currency: 'Currency',
    notifications: 'Notifications',
    users: 'Users',
    database: 'Database',
    security: 'Security',
    generalSettings: 'General Settings',
    organizationName: 'Organization Name',
    interfaceLanguage: 'Interface Language',
    timezone: 'Timezone',
    dateFormat: 'Date Format',
    saveChanges: 'Save Changes',
    currencySettings: 'Currency Settings',
    mainCurrency: 'Main Currency',
    exchangeRate: 'USD to UZS Rate',
    updateRate: 'Update Rate',
    currencyHint: 'Exchange rate is used for converting purchase and sale prices. We recommend updating the rate daily.',
    notificationSettings: 'Notification Settings',
    lowStockNotification: 'Low Stock',
    lowStockNotificationDesc: 'Notify when stock reaches minimum level',
    expiryNotification: 'Expiry Dates',
    expiryNotificationDesc: 'Notify 90 days before expiry',
    largeSalesNotification: 'Large Sales',
    largeSalesNotificationDesc: 'Notify for sales over 1,000,000 UZS',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Send important notifications via email',
    userManagement: 'User Management',
    addUser: 'Add User',
    user: 'User',
    role: 'Role',
    admin: 'Administrator',
    managerRole: 'Manager',
    cashier: 'Cashier',
    backupDatabase: 'Create Backup',
    restoreDatabase: 'Restore from Backup',
    drugsCount2: 'Drugs',
    inventoryRecords: 'Inventory Records',
    transactionsCount: 'Transactions',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    minChars: 'Minimum 8 characters',
    repeatPassword: 'Repeat new password',
    updatePassword: 'Update Password',

    // Drug forms
    tablets: 'Tablets',
    capsules: 'Capsules',
    solution: 'Solution',
    powder: 'Powder',
    gel: 'Gel',
    cream: 'Cream',
    syrup: 'Syrup',
    ointment: 'Ointment',
    drops: 'Drops',

    // CRUD operations
    deleteDrug: 'Delete Drug',
    confirmDelete: 'Are you sure you want to delete',
    noDrugsFound: 'No drugs found',
    addFirstDrug: 'Add your first drug to the catalog',
    noInventoryFound: 'Inventory is empty',
    deleteInventory: 'Delete Item',
    selectDrug: 'Select drug',
    selectPharmacy: 'Select pharmacy',
    selectSupplier: 'Select supplier',
    invoiceNumber: 'Invoice Number',

    // Time
    minAgo: 'min ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
  }
}

export type TranslationKey = keyof typeof translations.ru

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: TranslationKey) => string
  formatCurrency: (value: number) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('ru')

  useEffect(() => {
    const saved = localStorage.getItem('pharmacentral-lang') as Language
    if (saved && ['ru', 'uz', 'en'].includes(saved)) {
      setLang(saved)
    }
  }, [])

  const handleSetLang = (newLang: Language) => {
    setLang(newLang)
    localStorage.setItem('pharmacentral-lang', newLang)
  }

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.ru[key] || key
  }

  const formatCurrency = (value: number): string => {
    const suffix = lang === 'en' ? ' UZS' : ' сум'
    if (Math.abs(value) >= 1000000) {
      return (value / 1000000).toFixed(2) + 'M' + suffix
    }
    return value.toLocaleString('ru-RU') + suffix
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
